# Site settings

title: "RAD Transportation"
url: "http://radumas.info/blog"
baseurl: "/blog"
title_description: "Displaying projects, opinions, tutorials, etc. while working on transportation"
title_image: "http://radumas.info/blog/img/Bus_in_Rio_de_Janeiro.jpg"
keywords: "transportation, research, ghg, climate change, accessibility, tutorials, transit, data analysis"
favicon: "/favicons/favicon.ico"
google_analytics: false
#disqus_account: false
post_limit: 5

# Social usernames/URLs
twitter_username: dumasraphael
github_username:  radumas
linkedin_link: https://linkedin.com/in/DumasRaphael
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://gis.stackexchange.com/users/36886/raphael

#404-img: "/img/labtocat.png"

collections:
    presentations:
        output: true
    category:
        output: true

# Footer
footer_left: "Made by <a href=\"https://twitter.com/DumasRaphael\">Raphael Dumas</a>"
footer_right: "Carte-Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> <i class=\"fa fa-code-fork\"></i> on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
markdown: kramdown
kramdown: 
    input: GFM
    syntax_highlighter: rouge


#permalink: pretty
# Exclusion list from the generated _site
exclude: ["LICENSE", "_presentations/readme.md", "_category/readme.md", "vendor", "README.*", "otp", "_gps"]
