# Site settings

title: "MISTI Internship with The LTC"
url: "https://radumas.github.io/coppe-ltc"
baseurl: "coppe-ltc"
description: "Displaying projects, thoughts, etc. while working for the Laboratório de Transportes de Cargas at COPPE, the graduate engineering research school within the Federal University of Rio de Janeiro (UFRJ)"
keywords: "transportation, research, ghg, climate change, accessibility, rio de janeiro, coppe, ufrj, brasil"
favicon: "/favicons/favicon.ico"
#black-favicon: "/img/black-lab-glass.ico"
google_analytics: false
#disqus_account: false
post_limit: 5

# Social usernames/URLs
twitter_username: dumasraphael
github_username:  radumas
linkedin_link: https://linkedin.com/in/DumasRaphael
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://gis.stackexchange.com/users/36886/raphael


#404-img: "/img/labtocat.png"

# Footer
footer_left: "Made by <a href=\"https://twitter.com/DumasRaphael\">Raphael Dumas</a>"
footer_right: "Carte-Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> <i class=\"fa fa-code-fork\"></i> on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
# Exclusion list from the generated _site
exclude: ["LICENSE", "readme.md", "vendor"]
